name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main

env:
  APP_NAME: EtablissementGest

jobs:
  # Étape 1 : Récupération, Build, Tests, Qualité
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code source
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Supprimer le fichier .env
        run: rm -f .env

      - name: Build du projet (Install dependencies)
        run: composer install --no-scripts --no-interaction

      - name: Exécuter les migrations
        run: php artisan migrate --env=testing

      - name: Exécution des tests unitaires
        run: php artisan test

      - name: Exécution des tests IHM (Laravel Dusk)
        run: |
          php artisan serve --host=0.0.0.0 --port=8000 &
          php artisan dusk

      - name: Vérification de la qualité logicielle (PHPStan)
        run: |
          composer require --dev phpstan/phpstan
          ./vendor/bin/phpstan analyse
